# Site settings
title:          Richard Zhao
email:          richardz@andrew.cmu.edu
description: >
  Learner, calligrapher, and running enthusiast.

baseurl:  "" # the subpath of your site, e.g. /blog
url:      "http://richard-zhao.com" # the base hostname & protocol for your site

# Social
github:   zhaorz
disqus:   richardzhao
linkedin: zhaorz
facebook: "richard.zhao.7"

# Outputting
paginate:           5
paginate_path:      "blog/page:num"
excerpt_separator:  "<!--excerpt-->"

# Build settings
exclude:      [vendor]
markdown:     kramdown
highlighter:  rouge

gems:         [
  "jekyll-paginate"
  ]

