title:            Richard Zhao
description:

# Owner/author information
name:           Richard Zhao
email:          richardz@andrew.cmu.edu
github:         zhaorz
location:       "Pittsburgh, Pennsylvania"

# Site settings
timezone:    America/New_York
highlighter: pygments
markdown:    kramdown
excerpt_separator: "<!--excerpt-->"

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      [
                "lib", "config.rb", "Capfile", "config",
                "log", "Rakefile", "Rakefile.rb", "tmp",
                "CNAME", "Gemfile", "Gemfile.lock",
              ]
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Outputting
paginate:      3
paginate_path: blog/page:num
timezone:      null

# Assets
sass:
  sass_dir:   _sass
  style:      compressed

# Markdown Processor
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

