# Site settings
title:       Richard Zhao
email:       richardz@andrew.cmu.edu
author:      Richard Zhao
description: ""
baseurl:     ""
url:         "http://richard-zhao.com"

# Google analytics
google_analytics: 'UA-65056214-1'

exclude:      [
                "lib", "config.rb", "Capfile", "config",
                "log", "Rakefile", "Rakefile.rb", "tmp",
                "CNAME", "Gemfile", "Gemfile.lock",
              ]

# Outputting
paginate:      3
paginate_path: "blog/page:num"
excerpt_separator: "<!--excerpt-->"

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false
show_social_icons:  true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:   richardzhao

# Social icons
github_username:    zhaorz
stackoverflow_id:
twitter_username:
google_plus_id:
linkedin_username:  zhaorz
angellist_username:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: false
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:     redcarpet
#highlighter:  pygments
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
sass:
  compressed: true
gems:         [
                "jekyll-paginate"
              ]

# - jekyll-sitemap
