# Site settings
title:          Richard Zhao
email:          richardz@andrew.cmu.edu
description:

baseurl:  "" # the subpath of your site, e.g. /blog
url:      "http://richard-zhao.com" # the base hostname & protocol for your site

google_analytics: 'UA-65056214-1'

# Social
github:   zhaorz
disqus:   richardzhao
linkedin: zhaorz
facebook: "richard.zhao.7"
resume:   /assets/richard-zhao-resume.pdf

# Outputting
permalink:          /blog/:year/:month/:day/:title/
paginate:           5
paginate_path:      "blog/page:num"
excerpt_separator:  "<!--excerpt-->"

# Build settings
markdown:     kramdown
highlighter:  rouge
exclude:      [
  vendor, Gemfile, Gemfile.lock
]

gems:         [
  "jekyll-paginate"
  ]
